### ISSUE TITLE
KeyError: 'time' with  G_form=2; model tseb-pt

### ISSUE THREAD

**Issue by verenakuch96** [hectornieto/pyTSEB#40]
`Traceback (most recent call last):
  File "C:/Users/user/Documents/UNI/masterarbeit/Modelle_skript/TSEB/pyTSEB-master/pyTSEB-master/TSEB_local_image_main.py", line 37, in <module>
    run_TSEB_from_config_file(config_file)
  File "C:/Users/user/Documents/UNI/masterarbeit/Modelle_skript/TSEB/pyTSEB-master/pyTSEB-master/TSEB_local_image_main.py", line 29, in run_TSEB_from_config_file
    setup.run(is_image=True)
  File "C:\Users\user\Documents\UNI\masterarbeit\Modelle_skript\TSEB\pyTSEB-master\pyTSEB-master\pyTSEB\TSEBConfigFileInterface.py", line 269, in run
    model.process_local_image()
  File "C:\Users\user\Documents\UNI\masterarbeit\Modelle_skript\TSEB\pyTSEB-master\pyTSEB-master\pyTSEB\PyTSEB.py", line 193, in process_local_image
    self.G_form[1] = in_data['time']
KeyError: 'time'`

Error in File pyTSEB.py:193
`self.G_form[1] = in_data['time']`

Key Error by using TSEB_local_image_main trying to use G form 2 - all other G-forms are working.

Environment: 
- Windows 10
- Conda
- Python 3.7
- TSEB 2.1

Thank you for your help

**Comment by hectornieto** [comment]
Thanks for your feedback, 

I have just pushed a commit that should fix issue.

**Comment by verenakuch96** [comment]
Thank you for the quick fix. Now it is working
